name: GitHub Pages Build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: ðŸ›Žï¸ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for .GitInfo and .Lastmod
          lfs: true       # Fetch large files

      - name: Rebuilding Indexes
        run: make purge_indexes build/indexed 

      - name: Backing up Indexes
        uses: EndBug/add-and-commit@v9
        with: make purge_indexes build/indexed 
          message: Updated Index
          committer_name: GitHub Actions
          committer_email: actions@github.com

      - name: âŒ Turn off LFS
        run: >-
          git lfs uninstall;
          rm -Rf .git;
          rm .gitattributes;

      - name: ðŸš€ Deploy to `gh-pages` branch
        uses: peaceiris/actions-gh-pages@v3.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
